/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        primary: '#006591',
        'primary-container': '#2aabee',
        'on-primary': '#ffffff',
        'on-primary-container': '#003c58',
        'primary-fixed': '#c9e6ff',
        'primary-fixed-dim': '#89ceff',
        secondary: '#00658e',
        'secondary-container': '#54c0fd',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#004c6d',
        tertiary: '#845400',
        'tertiary-container': '#dd910f',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#503100',
        background: '#f6faff',
        'on-background': '#171c20',
        surface: '#f6faff',
        'on-surface': '#171c20',
        'surface-bright': '#f6faff',
        'surface-dim': '#d6dae0',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f4fa',
        'surface-container': '#eaeef4',
        'surface-container-high': '#e4e8ee',
        'surface-container-highest': '#dfe3e8',
        'surface-variant': '#dfe3e8',
        'on-surface-variant': '#3e4850',
        outline: '#6e7881',
        'outline-variant': '#bec8d2',
        telegram: {
          blue: '#2AABEE',
          darkBlue: '#229ED9',
          bgDark: '#17212B',
          cardDark: '#1C2733',
          bgLight: '#FFFFFF',
          cardLight: '#F7F9FB',
        },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        tg: '16px',
        full: '9999px',
      },
      spacing: {
        'edge-margin': '16px',
        'stack-sm': '8px',
        gutter: '12px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'container-max': '680px',
      },
      maxWidth: {
        'container-max': '680px',
      },
    },
  },
  plugins: [],
};
